services:
  django:
    container_name: django 

    build: ./webscrap
    ports:
      - "8000:8000"

    env_file:
      - .env
    volumes:
      - ./webscrap:/webscrap
      
    depends_on:
      - db
    networks:  
      - app-network
  db:
    container_name: db
    image: postgres:16.1-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  selenium:
    image: selenium/standalone-chrome:114.0
    container_name: selenium
    ports:
      - "4444:4444"
    networks:
      - app-network
volumes:
  pgdata: {}

networks:
  app-network:
    driver: bridge