# Generated by Django 5.2.7 on 2025-10-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('content_html', models.TextField()),
                ('content_text', models.TextField()),
                ('published_at', models.CharField(max_length=19)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
